version: '3.8'
services:
  filebeat:
    image: startupframework/filebeat:7.10.1
    container_name: filebeat
    environment:
      - HTTP_SERVICE_LOG=/var/log/http-service/
      - HTTP_SERVICE_LOG_FILES=*-ms.log
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
    volumes:
      - ./config/filebeat.yml:/etc/filebeat/filebeat.yml:ro
      - C:/var/log/http-service/:/var/log/http-service/
    networks:
      - elastic-network

networks:
  elastic-network:
    external: true
    name: elastic-network