apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: startup
  labels:
    app: filebeat
data:
  HTTP_SERVICE_LOG: /var/log/http-service/
  HTTP_SERVICE_LOG_FILES: "*-ms.log"
  LOGSTASH_HOST: logstash
  LOGSTASH_PORT: "5044"