apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: startup
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: filebeat
        image: startupframework/filebeat:7.10.1
        imagePullPolicy: IfNotPresent        
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        envFrom:
        - configMapRef:
            name: filebeat-config        
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: "/var/log/http-service/"
          name: http-service-logs
        - mountPath: /etc/filebeat/
          name: startup-filebeat-config
      volumes:
      - name: startup-filebeat-config
        configMap:
          name: startup-filebeat-config
          items:
          - key: "filebeat.yml"
            path: "filebeat.yml"
      - name: http-service-logs
        persistentVolumeClaim:
          claimName: http-service-logs-pv-claim