version: '3.8'

networks:
  security-network:
    driver: bridge

services:
  security-db-server: # Postgress database for Keycloak
    image: postgres:11.1-alpine
    container_name: security-db-server      
    environment:
      - POSTGRES_DB=security-db
      - POSTGRES_PASSWORD=msa
      - POSTGRES_USER=msa
    ports:
      - 5433:5432
    networks: 
      - security-network
    volumes:
      - security-db-data:/var/lib/postgresql/data
      
  authorization-server: # Embedded Keycloak Server Spring Boot
    image: startupframework/startup-msa-authorization-server:1.0.2.RELEASE
    container_name: authorization-server      
    environment:      
      - JAVA_OPTS_MEM=-Xmx512M -XX:MaxMetaspaceSize=256M -Xss366K 
      - SPRING_OPTS=
        --spring.profiles.active=local
        --eureka.instance.ip-address=127.0.0.1
        --spring.boot.admin.client.instance.prefer-ip=false
        --startup.dependencies=security-db-server:5432
      - DB_HOSTNAME=security-db-server
      - DB_PORT=5432
      - DB_DATABASE=security-db
      - DB_USER=msa
      - DB_PASS=msa
    ports:
      - 8085:8085
    networks:
      - security-network
    volumes:
      - logger:/var/log/spring-boot-app/
    depends_on:
      - security-db-server

volumes:
  logger:
    driver: local
  security-db-data:
    driver: local

