version: '3.8'

networks:
  spring-network:
    driver: bridge

services:
  discovery-server:
    image: startupframework/startup-msa-discovery-server:1.0.2.RELEASE
    container_name: discovery-server
    environment:
      - JAVA_OPTS_MEM=-Xmx74M -XX:MaxMetaspaceSize=80M -Xss366K
      - SPRING_OPTS=
          --server.port=8761
          --spring.profiles.active=local
          --eureka.instance.ip-address=localhost
          --eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
    ports:
      - 8761:8761
    networks:
      - spring-network
    volumes:
      - logger:/var/log/spring-boot-app/

  config-server:
    image: startupframework/startup-msa-config-server:1.0.2.RELEASE
    container_name: config-server
    environment:      
      - JAVA_OPTS_MEM=-Xmx74M -XX:MaxMetaspaceSize=80M -Xss366K
      - SPRING_OPTS=
        --server.port=8762
        --spring.profiles.active=local
        --spring.cloud.config.server.git.uri=https://github.com/israel-anaya/startupframework-demo-config.git 
        --spring.cloud.config.server.git.force-pull=true
        --eureka.instance.ip-address=localhost
        --eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
        --startup.dependencies=discovery-server:8761
    ports:
      - 8762:8762
    networks:
      - spring-network
    volumes:
      - logger:/var/log/spring-boot-app/
    depends_on:
      - discovery-server

  edge-server:
    image: startupframework/startup-msa-edge-server:1.0.2.RELEASE
    container_name: edge-server      
    environment:      
      - JAVA_OPTS_MEM=-Xmx74M -XX:MaxMetaspaceSize=80M -Xss366K
      - SPRING_OPTS=
        --server.port=8080
        --spring.profiles.active=local
        --spring.cloud.config.discovery.enabled=false
        --spring.cloud.config.uri=http://config-server:8762
        --eureka.instance.ip-address=localhost
        --eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
        --startup.dependencies=discovery-server:8761,config-server:8762
    ports:
      - 8080:8080
    networks:
      - spring-network
    volumes:
      - logger:/var/log/spring-boot-app/
    depends_on:
      - discovery-server
      - config-server

volumes:
  logger:
    driver: local

