version: '3.8'

networks:
  spring-network:
    driver: bridge

services:
  redis-cache: # Redis Cache for MSA
    image: redis:alpine
    container_name: redis-cache
    ports:
      - 6379:6379
    networks:
      - spring-network

  msa-db: # Postgress database for MSA
    image: postgres:11.1-alpine
    container_name: msa-db-server      
    environment:
      POSTGRES_DB: postgres-msa-db
      POSTGRES_PASSWORD: msa
      POSTGRES_USER: msa
    ports:
      - 5432:5432
    networks: 
      - spring-network
    volumes:
      - msa-db-data:/var/lib/postgresql/data
      
  discovery-server: # Discovery Server
    image: startupframework/startup-msa-discovery-server:1.0.2.RELEASE
    container_name: discovery-server
    environment:
      - JAVA_OPTS_MEM=-Xmx74M -XX:MaxMetaspaceSize=80M -Xss366K 
      - SPRING_OPTS=
        --server.port=8761
        --spring.profiles.active=local
        --eureka.instance.preferIpAddress=true
        --eureka.instance.ip-address=127.0.0.1
        --eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
        --management.endpoints.web.exposure.include=*
        --management.endpoint.health.show-details=ALWAYS
        --spring.boot.admin.client.instance.prefer-ip=true
        --startup.dependencies=redis-cache:6379,msa-db:5432
    ports:
      - 8761:8761
    networks:
      - spring-network
    volumes:
      - logger:/var/log/spring-boot-app/
      #- shareclasses:/var/log/spring-boot-app/shareclasses

  config-server: # Config Server
    image: startupframework/startup-msa-config-server:1.0.2.RELEASE
    container_name: config-server
    environment:      
      - JAVA_OPTS_MEM=-Xmx74M -XX:MaxMetaspaceSize=80M -Xss366K 
      - SPRING_OPTS=
        --server.port=8762
        --spring.profiles.active=local
        --spring.cloud.config.server.git.uri=https://github.com/israel-anaya/startupframework-demo-config.git 
        --spring.cloud.config.server.git.force-pull=true
        --eureka.instance.ip-address=127.0.0.1
        --eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
        --management.endpoints.web.exposure.include=*
        --management.endpoint.health.show-details=ALWAYS
        --startup.dependencies=discovery-server:8761
    ports:
      - 8762:8762
    networks:
      - spring-network
    volumes:
      - logger:/var/log/spring-boot-app/
      #- shareclasses:/var/log/spring-boot-app/shareclasses
    depends_on:
      - discovery-server

  edge-server: #Edge Server or Gateway
    image: startupframework/startup-msa-edge-server:1.0.2.RELEASE
    container_name: edge-server      
    environment:      
      - JAVA_OPTS_MEM=-Xmx74M -XX:MaxMetaspaceSize=80M -Xss366K 
      - SPRING_OPTS=
        --server.port=8080
        --spring.profiles.active=local
        --spring.cloud.config.discovery.enabled=false
        --spring.cloud.config.uri=http://config-server:8762
        --eureka.instance.ip-address=127.0.0.1
        --eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
        --management.endpoints.web.exposure.include=*
        --management.endpoint.health.show-details=ALWAYS
        --startup.dependencies=discovery-server:8761,config-server:8762
    ports:
      - 8080:8080
    networks:
      - spring-network
    volumes:
      - logger:/var/log/spring-boot-app/
      #- shareclasses:/var/log/spring-boot-app/shareclasses
    depends_on:
      - discovery-server
      - config-server

  admin-server: # Spring Boot Admin
    image: startupframework/startup-msa-admin-server:1.0.2.RELEASE
    container_name: admin-server      
    environment:      
      - JAVA_OPTS_MEM=-Xmx74M -XX:MaxMetaspaceSize=80M -Xss366K 
      - SPRING_OPTS=
        --server.port=8081
        --spring.profiles.active=local
        --spring.cloud.config.discovery.enabled=false
        --spring.cloud.config.uri=http://config-server:8762
        --eureka.instance.ip-address=127.0.0.1
        --spring.boot.admin.client.instance.prefer-ip=false
        --eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/        
        --management.endpoints.web.exposure.include=*
        --management.endpoint.health.show-details=ALWAYS 
        --spring.boot.admin.discovery.ignored-services=*msa*       
        --spring.cloud.discovery.client.simple.instances.architecture[0].uri=http://discovery-server:8761
        --spring.cloud.discovery.client.simple.instances.architecture[0].metadata.management.context-path=/actuator
        --spring.cloud.discovery.client.simple.instances.architecture[1].uri=http://config-server:8762
        --spring.cloud.discovery.client.simple.instances.architecture[1].metadata.management.context-path=/actuator
        --spring.cloud.discovery.client.simple.instances.architecture[2].uri=http://edge-server:8080
        --spring.cloud.discovery.client.simple.instances.architecture[2].metadata.management.context-path=/actuator
        --startup.dependencies=discovery-server:8761,config-server:8762,edge-server:8080
    ports:
      - 8081:8081
    networks:
      - spring-network
    volumes:
      - logger:/var/log/spring-boot-app/
      #- shareclasses:/var/log/spring-boot-app/shareclasses
    depends_on:
      - discovery-server
      - config-server

volumes:
  logger:
    driver: local
  msa-db-data:
    driver: local

