---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: startup-msa-config-server
    provider: jkube
    version: 1.0.2.RELEASE
    group: org.startupframework
  name: startup-msa-config-server
  namespace: startup
data:
  JAVA_OPTS_MEM: -Xmx74M -XX:MaxMetaspaceSize=80M -Xss366K
  SPRING_OPTS: --server.port=8080 --spring.profiles.active=dev --spring.cloud.config.server.git.uri=https://github.com/israel-anaya/startupframework-demo-config.git  --spring.cloud.config.server.git.force-pull=true
    --eureka.client.serviceUrl.defaultZone=http://startup-msa-discovery-server/eureka/
    --management.endpoints.web.exposure.include=* --management.endpoint.health.show-details=ALWAYS
    --startup.dependencies=startup-msa-discovery-server:80
