version: '2.2'
services:
  elasticsearch-node-01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: elasticsearch-node-01
    environment:
      - node.name=elasticsearch-node-01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-node-02,elasticsearch-node-03
      - cluster.initial_master_nodes=elasticsearch-node-01,elasticsearch-node-02,elasticsearch-node-03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  elasticsearch-node-02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: elasticsearch-node-02
    environment:
      - node.name=elasticsearch-node-02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-node-01,elasticsearch-node-03
      - cluster.initial_master_nodes=elasticsearch-node-01,elasticsearch-node-02,elasticsearch-node-03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9201
    networks:
      - elastic

  elasticsearch-node-03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: elasticsearch-node-03
    environment:
      - node.name=elasticsearch-node-03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-node-01,elasticsearch-node-02
      - cluster.initial_master_nodes=elasticsearch-node-01,elasticsearch-node-02,elasticsearch-node-03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    ports:
      - 9202:9202
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-node-01:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch-node-01:9200
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge