apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: startup
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30200 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: startup
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"] 
        args: ["-c", "chown -R 1000:0 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true        
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: elasticsearch-config
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 512Mi
        ports:
        - name: http-service
          containerPort: 9200
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: http-service
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: http-service
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"                                
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-pv-claim        
