apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: startup
  labels:
    app: kibana
data:
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"